# ~/Projects/compliment/echosignal_project/docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    # Опционально: проброс порта БД на НЕСТАНДАРТНЫЙ порт хоста
    # Используем 5434, чтобы не конфликтовать с портом 5432 или 5433 от compliment-monorepo
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    # Пробрасываем порт 8000 контейнера на НЕСТАНДАРТНЫЙ порт 8001 хоста
    # Чтобы не конфликтовать с портом 8000 от compliment-monorepo
    ports:
      - "8001:8000"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST} # Должно быть 'db'
      - DATABASE_PORT=${DATABASE_PORT} # Должно быть 5432 (внутренний порт контейнера db)
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
